project:
  type: website

website:
  title: "Italiaans studeren"
  navbar:
    right:
      - grammatica.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: flatly
    css: styles.css

editor: visual

